name: Update Formula

on:
  repository_dispatch:
    types: [punkdoku-updated]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Formula
        run: |
          # Get version from event
          VERSION="${{ github.event.client_payload.version }}"
          TAG="${{ github.event.client_payload.tag }}"
          
          # Download and calculate SHA256 for macOS arm64
          curl -L "https://github.com/daypunk/punkdoku/releases/download/${TAG}/punkdoku-macos-arm64" -o punkdoku-macos-arm64
          SHA256_ARM64=$(shasum -a 256 punkdoku-macos-arm64 | cut -d' ' -f1)
          
          # Download and calculate SHA256 for macOS amd64
          curl -L "https://github.com/daypunk/punkdoku/releases/download/${TAG}/punkdoku-macos-amd64" -o punkdoku-macos-amd64
          SHA256_AMD64=$(shasum -a 256 punkdoku-macos-amd64 | cut -d' ' -f1)
          
          # Update Formula/punkdoku.rb
          sed -i "s/version \".*\"/version \"${VERSION}\"/" Formula/punkdoku.rb
          sed -i "s/sha256 \".*\"/sha256 \"${SHA256_ARM64}\"/" Formula/punkdoku.rb
          
          # Commit and push
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/punkdoku.rb
          git commit -m "Update punkdoku to ${VERSION}"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update punkdoku to ${{ github.event.client_payload.version }}"
          body: "Automated update from punkdoku release"
          branch: update-punkdoku-${{ github.event.client_payload.version }}
